### PR TITLE
Update to BinSync version 4

### PR DESCRIPTION
**Pull request by mahaloz**

### CODE REVIEW

**Comment by twizmwazin** [comment]
@mahaloz Can you test using one one of the pyinstaller artifacts produced by the bundle job? If everything works there as expected then this lgtm.

**Comment by mahaloz** [comment]
@twizmwazin when I use the PyInstaller version I get an import error for things that clearly exist:
```
WARNING | 12:15:51 | angrmanagement.plugins.plugin_manager | Exception occurred during plugin loading: No module named 'binsync.interface_overrides.angr'
NoneType: None
```

Here is the file:
https://github.com/binsync/binsync/blob/main/binsync/interface_overrides/angr.py

**Comment by mahaloz** [comment]
Do I need to somehow specify them with:
```
__all__ = ["angr"]
```
Or something?

**Comment by twizmwazin** [comment]
No module means that pyinstaller didn't find it when searching the import graph. Try pushing a commit adding the import to [this list](https://github.com/angr/angr-management/blob/master/angr-management.spec#L82) and seeing if that fixes it

**Comment by mahaloz** [comment]
@twizmwazin we are good to go

**Pull request merged**
