### PR TITLE
Fix #69, thread termination

### LINKED ISSUE #69: Error message when exiting: "QThread: Destroyed while thread is still running"
After merging in #67, I get this error message when quitting angr management all the time. Maybe there is a thread left running? @sraboy

### PR DESCRIPTION
**Pull request by sraboy**
This is still not terribly robust and it relies on plugins being nice enough to stop themselves when asked.

### CODE REVIEW

**Comment by sraboy** [comment]
Sorry, forgot to merge master before opening the PR. Fixed the conflicts though so you should just get two commits on merge.

**Comment by ltfish** [comment]
Wait we are getting all these conflicts for some reason...

**Comment by sraboy** [comment]
ARGH!

**Comment by sraboy** [comment]
For some reason GitHub did not recognize that I force-pushed over the conflicts. Those conflicts literally did not exist after pushing. I've manually resolved them via the web interface here.

**Pull request merged**
