### PR TITLE
Add Simgr Toolbar

### PR DESCRIPTION
**Pull request by yuzeming**
* merge `StatesToolbar` and `AnalysisToolbar` into `SimgrToolbar` and add more bottoms
* add [QtAwesome](https://github.com/spyder-ide/qtawesome) as a icons source
* add `pypcode` in `install_requires`

Screenshot at 2021-10-14 17-22-32

### CODE REVIEW

**Comment by ltfish** [comment]
Why are we adding a hard dependency on pypcode?

**Comment by ltfish** [comment]
Importing QtAwesone makes our test cases fail. Can you fix them?

**Comment by yuzeming** [comment]
```
======================================================================
ERROR: test_address_conversion (test_qaddress_input.TestQaddressInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/1/s/build/src/angr-management/tests/test_qaddress_input.py", line 20, in test_address_conversion
    main = MainWindow(show=False)
  File "/__w/1/s/build/src/angr-management/angrmanagement/ui/main_window.py", line 95, in __init__
    self._init_toolbars()
  File "/__w/1/s/build/src/angr-management/angrmanagement/ui/main_window.py", line 214, in _init_toolbars
    self._simgr_toolbar = SimgrToolbar(self)
  File "/__w/1/s/build/src/angr-management/angrmanagement/ui/toolbars/simgr_toolbar.py", line 17, in __init__
    ToolbarAction(qta.icon("fa5s.plus"),"New", "Start a new Simulation...", \
  File "/__w/1/s/build/virtualenv/lib/python3.6/site-packages/qtawesome/__init__.py", line 173, in icon
    return _instance().icon(*names, **kwargs)
  File "/__w/1/s/build/virtualenv/lib/python3.6/site-packages/qtawesome/__init__.py", line 77, in _instance
    'materialdesignicons-webfont-charmap.json')
  File "/__w/1/s/build/virtualenv/lib/python3.6/site-packages/qtawesome/iconic_font.py", line 214, in __init__
    self.load_font(*fargs)
  File "/__w/1/s/build/virtualenv/lib/python3.6/site-packages/qtawesome/iconic_font.py", line 270, in load_font
    os.path.join(directory, ttf_filename)))
qtawesome.iconic_font.FontError: Font at '/__w/1/s/build/virtualenv/lib/python3.6/site-packages/qtawesome/fonts/fontawesome4.7-webfont.ttf' appears to be empty. If you are on Windows 10, please read https://support.microsoft.com/en-us/kb/3053676 to know how to prevent Windows from blocking the fonts that come with QtAwesome.
```

It seem some ttf don't appear in the test environment

**Comment by yuzeming** [comment]
Add enable_fonts for qtawesome in ci-settings
https://github.com/angr/ci-settings/pull/23

**Pull request merged**
