### PR TITLE
Allow angr-management's log widget to capture subprocess logging

### PR DESCRIPTION
**Pull request by zwimer**
Fixes: https://github.com/angr/angr-management/issues/783

As I have an M1, my testing ability is limited.

Requires:
- [x] https://github.com/angr/angr/pull/3613

### CODE REVIEW

**Comment by zwimer** [comment]
@mborgerson I should note that this change only synchronized the EventSentinel parts. That is, the following line is *not* synchronized between processes:
https://github.com/angr/angr-management/blob/f058fb1e2a5910445f2be4f067e6f2cf30ed24ed/angrmanagement/data/log.py#L29
Only this is:
https://github.com/angr/angr-management/blob/f058fb1e2a5910445f2be4f067e6f2cf30ed24ed/angrmanagement/data/log.py#L30

**Comment by rhelmot** [comment]
Two main issues I have with this, which should probably be solved at the same time:

- One thread per sentinel seems like a lot
- sentinels do not have unbounded lifetimes, they should have their threads (or references in whatever one thread handles the dispatch) cleaned up on `__del__`.

**Comment by zwimer** [comment]
@rhelmot Their daemonic thread should terminate not long after their lifetime, the loop body takes in a weak reference to self for this reason. Or were you referring to making a `join()` call on the EventSentinel `__del__`?

Regarding one thread per sentinel; it shouldn't be an issue since right now it's only used for logging, but if you are trying to future-proof, what I can do is make a single dispatch thread that has a `dict` of `weakptr.Proxy` objects mapped to `EventSentinel`; this thread would basically preform the same actions as the present one except it would remove dead proxies from the set it is monitoring rather than die along with a proxy; and `time.sleep(.01)` or something if there are no items in the set. Thoughts?

**Comment by zwimer** [comment]
After further investigation, I've noticed this doesn't fix the problem. It does allow async / interprocess EventSentinels, but it seems like child processes do not have the logging handlers set themselves.

If we do want to keep the async abilities introduce by this PR I can re-create this PR, but it will not fundamentally fix: https://github.com/angr/angr-management/issues/783

To fix this issue, I see the three options:

#### Manually adding handlers each time

Each `multiprocessing.Process` would have to add a logging manually (or via some function); perhaps a `logging.QueueHandler` wrapping a `multiprocessing.Queue`. The downside of this

The downside of this is that we can only do this for the `multiprocessing.Process` that `angr-mangagement` directly spawns; that is to say the `multiprocessing.Process` calls in `angr` itself and below would not install this logging module, thus their messages would be missed.

#### Remapping stdout / stderr

If we remap `stdout` (and perhaps `stderr`) to a pipe, then the processes' default handlers will simply write their log messages to a pipe. We could then change the base process' logging handler to output to the 'new' stdout/stderr. Maybe something like:
```python
# Remap stderr
real_stderr = sys.stderr
log_pipe_read, log_pipe_write = os.pipe()
sys.stderr = log_pipe_write
# Allow main process to log to stderr
logging.addHandler(logging.StreamHandler(real_stderr)
# New children processes will now log to: log_pip_write
```

The downside here is that we would only be able to get text from these messages; so we would have to strip out the ansi escape codes `angr` and parse the log message; probably `msg.split("|", maxsplit=4)`.

#### Forcing every process to load a given file 

Is there some sort of `LD_PRELOAD` equivalent for `multiprocessing.Process`? I know there is for pools, but just for `Process`? I can think of a few hacky ways to do this, but none that are actually 'good'. This would be the ideal solution, having each process just add the new logging handler themselves on init, but I don't know how to accomplish this.

**Comment by rhelmot** [comment]
The equivalent of LD_PRELOAD for multiprocessing.Process is that it will attempt to re-import the `__main__` module in each process. You can detect that it isn't the main process because `__name__ != '__main__'`. This is the correct solution I believe.

**Comment by zwimer** [comment]
@rhelmot It's `__mp_main__`, but that only runs on files the process loads; but subprocesses won't necessarily load the code with this.

To test this I inserted file writes in the `bin/angrmanagement` file along with the top level `__init__.py` and `__main__.py` files that would only trigger on `__mp_main__`. I saw no writes when launching angr-management then loading `/bin/false`; despite noticing angr-management said it was spawning workers (this should have spawned angr processes for variable recovery I think).

Is there perhaps an `LD_PRELOAD`-like hook for `multiprocessing.Process` that uses `POpen`'s `preexec_fn` or something? Since I don't know if we can rely on any given python file to import for certain. At least as far as I'm aware. I also checked for all `__name__` to see if it was something like `angrmanagement.__mp_main__` but only the main process ever invoked this code so no `multiprocessing.Process`' ever ran this code.

**Comment by zwimer** [comment]
Unless we manually add a callback to every `multiprocessing.Process` target functions in both `angr`, `angr-management`, and others.

**Comment by rhelmot** [comment]
Looked into it a bit more. I believe this is a problem with the `spawn` vs `fork` start methods. spawn will re-import `__mp_main__` but fork will not. Since we are using fork on linux there is no way to hook process start.

I believe the only solution is for each analysis which can be multiprocessed to manually manage its own logs. We can provide a tool in angr (`angr.utils.logging.log_to_parent()`) to make this significantly easier.

**Comment by twizmwazin** [comment]
@rhelmot Python has a way to set pre- and post-fork callbacks https://docs.python.org/3/library/os.html#os.register_at_fork

**Comment by zwimer** [comment]
I was testing on macOS

**Comment by zwimer** [comment]
In this case, I will just have angr hold some contextual object meant to hold IPC objects which it will pass to each `multiprocessing.Process` invocation as an arg. For example `ipc = { "logging": multiprocessing.Queue() }` (or as a named tuple or something). This could be private; with perhaps public methods for things like `init_process()` which might hook up logging or other IPC related things that should remain across all subprocesses, as @rhelmot seconded earlier.

**Comment by zwimer** [comment]
CI is only failing for linting for push, not pull request, because the linting is complaining about items in angr not existing since it isn't checking out the PR branch of angr this PR depends on (the pull request version does though)

**Comment by zwimer** [comment]
@mborgerson This should fix the issue now that the related PR has been merged into angr.

**Comment by zwimer** [comment]
I cannot test this for Linux. It's only been tested on macos

**Comment by zwimer** [comment]
Tested on both macOS and ubuntu; this should cover both fork and spawn as well.

**Comment by mborgerson** [comment]
Thanks!

**Pull request merged**
