### PR TITLE
Update BinSync to version 2.2.0

### PR DESCRIPTION
**Pull request by mahaloz**

### CODE REVIEW

**Comment by mahaloz** [comment]
I would love to change how we do this, so this will be the last time I update code manually like this. Ideally we should have some type of remote loading plugin system @rhelmot.

**Comment by ltfish** [comment]
Redesigning the plugin loading is definitely on our plate but it's not of a high priority.

**Comment by mahaloz** [comment]
@ltfish if you want a quick and dirty hack, we could always just submodule binsync

**Comment by ltfish** [comment]
Please no. I'm about to remove the submodules in this repo...

**Pull request merged**
