### PR TITLE
Allow C-c to kill angr-management

### PR DESCRIPTION
**Pull request by mborgerson**
For when you just want to kill it, allow C-c/SIGINT

### CODE REVIEW

**Comment by ltfish** [comment]
You can use Ctrl+C to kill running python routines in the embedded IPython shell. Does this conflict with that?

I’m not sure we want to include such a hot key for a GUI program.

**Comment by zardus** [comment]
The number of times I tried to ctrl-c angr-management to no avail... IMO,
we should quit when ctrl-c is hit. Individual processes should be killable
via the GUI (some sort of Jobs panel), ideally...

**Comment by ltfish** [comment]
Does gedit or notepad quite when Ctrl-C is hit?

**Comment by ltfish** [comment]
We can add a hot key that kills angr management as long as it does not conflict with existing hot keys or user habits.

**Comment by mborgerson** [comment]
Sorry for the confusion, this is not to kill angr-management when Ctrl+C is pressed within the GUI, this is when you are at the console you launched angr-management and you press C-c to kill the running process like you would with other GUI apps launched from command line. e.g. if you start `gedit` then ctrl+c, gedit dies.

**Comment by ltfish** [comment]
I would assume that it will not work on Windows? Can you wrap it inside a platform check?

**Comment by mborgerson** [comment]
According to https://docs.python.org/3/library/signal.html this should work on Windows too, but I can wrap it if you prefer

**Comment by ltfish** [comment]
Let's merge and see :)

**Pull request merged**
