### PR TITLE
added plugin for logging user fatigueness

### LINKED ISSUE #252: Add Log Fatigue Plugin to store user fatiguness details remotely

### PR DESCRIPTION
**Pull request by Adersh97**
closes #252

### CODE REVIEW

**Comment by ltfish** [comment]
Hey, please do not add any code to MainWindow. Everything should be contained in your plugin, so that when your plugin is not loaded, no one needs to enter their user name when using angr management.

**Review by ltfish — CHANGES_REQUESTED** [review]
Commented above.

**Comment by Adersh97** [comment]
> Commented above.

I have made the requested changes. Thank you

**Comment by rhelmot** [comment]
A couple of requests from me:

1) Fix lint:

```
LINT FAILURE: new file angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py lints at 7.69/10.00. Errors:
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:6:0: E0401: Unable to import 'slacrs' (import-error)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:7:0: E0401: Unable to import 'slacrs.model' (import-error)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:34:8: C0415: Import outside toplevel (threading) (import-outside-toplevel)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:40:8: C0415: Import outside toplevel (time.sleep) (import-outside-toplevel)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:57:12: C0415: Import outside toplevel (math) (import-outside-toplevel)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:63:12: C0415: Import outside toplevel (time) (import-outside-toplevel)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:51:26: W0613: Unused argument 'obj' (unused-argument)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:106:29: W0613: Unused argument 'event' (unused-argument)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:43:8: W0201: Attribute 'slacr' defined outside __init__ (attribute-defined-outside-init)
... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:44:8: W0201: Attribute 'session' defined outside __init__ (attribute-defined-outside-init)
```

slacrs should be made into an optional import so that the plugin doesn't crash with import errors if it's not installed.

If a warning can't be worked around you can as a last resort disable it using a `# pylint: disable=message-name` comment. If you want to run pylint locally you can use [this pylintrc file](https://github.com/angr/angr-dev/blob/master/pylintrc) as configuration.

2) Add this plugin to the [default plugin blacklist](https://github.com/angr/angr-management/blob/master/angrmanagement/config/config_manager.py#L72) so that ordinary users of angr-management don't see the popup asking for their name

3) Figure out a way to not have to do `self._main_window.eventFilter = self.eventFilter`. You should be able to create a filter class which you can apply to the main window instead of applying the main window as its own event filter.

4) Make sure you tear down all your resources - stop the thread and uninstall the event filter - on plugin termination. It seems like you already found the `teardown` method, though you seem to have accidentally put it on the modal class instead of on the plugin class.

Feel free to ask here if you have any questions!

**Comment by Adersh97** [comment]
> A couple of requests from me:
> 
> 1. Fix lint:
> 
> ```
> LINT FAILURE: new file angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py lints at 7.69/10.00. Errors:
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:6:0: E0401: Unable to import 'slacrs' (import-error)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:7:0: E0401: Unable to import 'slacrs.model' (import-error)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:34:8: C0415: Import outside toplevel (threading) (import-outside-toplevel)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:40:8: C0415: Import outside toplevel (time.sleep) (import-outside-toplevel)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:57:12: C0415: Import outside toplevel (math) (import-outside-toplevel)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:63:12: C0415: Import outside toplevel (time) (import-outside-toplevel)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:51:26: W0613: Unused argument 'obj' (unused-argument)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:106:29: W0613: Unused argument 'event' (unused-argument)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:43:8: W0201: Attribute 'slacr' defined outside __init__ (attribute-defined-outside-init)
> ... angrmanagement/plugins/log_fatigue/log_fatigue_plugin.py:44:8: W0201: Attribute 'session' defined outside __init__ (attribute-defined-outside-init)
> ```
> 
> slacrs should be made into an optional import so that the plugin doesn't crash with import errors if it's not installed.
> 
> If a warning can't be worked around you can as a last resort disable it using a `# pylint: disable=message-name` comment. If you want to run pylint locally you can use [this pylintrc file](https://github.com/angr/angr-dev/blob/master/pylintrc) as configuration.
> 
> 1. Add this plugin to the [default plugin blacklist](https://github.com/angr/angr-management/blob/master/angrmanagement/config/config_manager.py#L72) so that ordinary users of angr-management don't see the popup asking for their name
> 2. Figure out a way to not have to do `self._main_window.eventFilter = self.eventFilter`. You should be able to create a filter class which you can apply to the main window instead of applying the main window as its own event filter.
> 3. Make sure you tear down all your resources - stop the thread and uninstall the event filter - on plugin termination. It seems like you already found the `teardown` method, though you seem to have accidentally put it on the modal class instead of on the plugin class.
> 
> Feel free to ask here if you have any questions!

Hello, thank you for the review, I have solved all of your comments, please let me know if you have any

**Comment by rhelmot** [comment]
Looks great! Thanks for the contribution.

**Pull request merged**
