### PR TITLE
Refactor: Instance Based Views

### PR DESCRIPTION
**Pull request by mahaloz**
In most cases, a View (like disassembly view), is created using the `workspace` with the use of the `instance` object. In effect, the instance object is a class that contains all the data of an angr project. To allow angr-management to have more than a single version of a View open, we must make views based on `instance` not on workspace. 

In this update, I refactor A LOT of code so that most references to workspace are exchanged with instance. This allows us, for instance, to load two binaries in at the same time in angr-management and do cool comparison stuff.

Using this PR code, here is a preliminary implementation for #729, to allow for recompilation and object difference viewing. Attached is a screen shot of this. I may move the plugin code that does this to a different PR, but for now it shows a nice way of why decoupling views from Workspace is essential and how you can test it. 

## Binary Diffing on ASM Level
recompilation

### CODE REVIEW

**Comment by mahaloz** [comment]
@mborgerson, you may be interested in how this is done :)

**Comment by zardus** [comment]
Wait, what... You made a-m support multiple angr projects??? It seems awesome in retrospect, but that's one of these ideas that simply never occurs to people!

**Comment by mahaloz** [comment]
@zardus No Binary is an Island. Hehe. But as you may have realized, being able to support multiple binaries loaded into angr management at the same time makes for some interesting implementation opportunities.

One I discussed with @ltfish was the ability to load library binaries in with a main loader and correct xrefs to them for some sick reversing of multi-bin targets.

**Comment by mahaloz** [comment]
For any who review this PR, please don't merge without talking to me first. I will likely move the BinDiff code to another PR.

**Comment by ltfish** [comment]
> Wait, what... You made a-m support multiple angr projects??? It seems awesome in retrospect, but that's one of these ideas that simply never occurs to people!

It has been the idea since the very early days of angr management, and the workspace/instance structure has always been designed to make that feasible. It's just that I never had enough energy to implement the support for it. Now that we have @mahaloz ... ;)

**Comment by mahaloz** [comment]
@ltfish the plugin code is moved to #740

**Review by ltfish — APPROVED** [review]

**Pull request merged**
