### PR TITLE
Add macos smoketest

### PR DESCRIPTION
**Pull request by twizmwazin**

### CODE REVIEW

**Comment by twizmwazin** [comment]
This is probably failing because macos is calling the process "angr-management" rather than "angr management". On linux and windows, we are checking window titles rather than process names. Is there a way we can modify the applescript snippet to do that @zwimer?

**Comment by zwimer** [comment]
Is it undesired to modify the app name to be `angr management.app` rather than `angr-management.app`? To answer your question though, I'll send you the code.

**Comment by zwimer** [comment]
Alternatively, change:
`tell application "Finder" to get name of every process whose name contains "angr management"`
to
`tell application "Finder" to get name of every process whose name contains "angr-management"`

**Comment by twizmwazin** [comment]
Checking process names is checking something different than checking window display names.

**Comment by zwimer** [comment]
@twizmwazin 
```
zwimer@Lotus ~> osascript -e 'tell application "System Events" to get name of every window of processes whose name contains "angr management"'
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, angr management,
```
If not windows is open: `,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,`

Note that the `,` output is due to applescript formatting the output as a string. The non-string output looks like:
```
{{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {"angr management"}}
```
Parse the `,` output as you like.

---

If you prefer, you can also do:
```
zwimer@Lotus ~> osascript -e 'tell application "System Events" to get (name of every window of processes whose name contains "angr management") as string'
angr management
```
If not windows is open, nothing is written to stdout.

This method is more of a `''.join([str(i) for i in results])`; that is, all window names will just be concatenated.

**Pull request merged**
