### PR TITLE
implementation of MultiTrace + Heatmap w/ SLACRS support

### PR DESCRIPTION
**Pull request by capysix**

### CODE REVIEW

**Comment by rhelmot** [comment]
I don't see any problems with this. Fix lint and I'll hit merge.

**Comment by twizmwazin** [comment]
Should the print statements be swapped out for log messages?

**Comment by rhelmot** [comment]
Oops, didn't see that. Yes, they should be. Use `workspace.log()`.

**Comment by capysix** [comment]
Would it be better for me to rebase and squash all my linting fixes before merging?

**Comment by rhelmot** [comment]
We have a handy squash-merge button for this exact purpose :)

**Pull request merged**
